In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, LogisticRegression
from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score
)

In [4]:
df = pd.read_csv("cleaned_data.csv")
df.head()

   Name  Age  Gender Department       City Education  Experience  Salary
0  Emp1   29  Female         IT  Bengaluru   Diploma           7   72779
1  Emp2   56  Female         HR    Chennai   Diploma          34  123382
2  Emp3   36    Male  Marketing  Bengaluru    Master          10   96128
3  Emp4   48  Female  Marketing  Hyderabad   Diploma          25  105715
4  Emp5   49  Female         IT  Bengaluru  Bachelor          25  117974

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        200 non-null    object
 1   Age         200 non-null    int64
 2   Gender      200 non-null    object
 3   Department  200 non-null    object
 4   City        200 non-null    object
 5   Education   200 non-null    object
 6   Experience  200 non-null    int64
 7   Salary      200 non-null    int64
dtypes: int64(3), object(5)
memory usage: 12.6+ KB

In [6]:
df.describe()

              Age  Experience         Salary
count  200.000000  200.000000     200.000000
mean    39.560000   15.080000   97142.520000
std     11.192532   11.195548   23379.035511
min     22.000000    0.000000   55291.000000
25%     29.000000    5.000000   76934.000000
50%     38.000000   13.000000   94602.500000
75%     49.000000   25.000000  117668.000000
max     60.000000   38.000000  146472.000000